services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - staticbuild:/app/static
    networks:
      - frontend

  nginx:
    depends_on:
      - nextjs
    build:
      context: ./nginx
    volumes:
      - staticbuild:/usr/share/nginx/html
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    ports:
      - "80:80"
      - "443:443"
    networks:
      - frontend

networks:
  frontend:
    driver: bridge

volumes:
  staticbuild:
