services:
  next_build:
    build:
      context: .
      dockerfile: Dockerfile.build
    ports:
      - "3000:3000"
    networks:
      - frontend

  next_static:
    build:
      context: .
      dockerfile: Dockerfile.static
    volumes:
      - staticbuild:/app/dist
    networks:
      - frontend

  nginx:
    build:
      context: ./nginx
    volumes:
      - staticbuild:/usr/share/nginx/html
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    ports:
      - "80:80"
      - "443:443"
    networks:
      - frontend

networks:
  frontend:
    driver: bridge

volumes:
  staticbuild:
