services:
  cache:
    image: redis:7-alpine
    restart: always
    expose:
      - 6379
    command: redis-server --save 20 1 --loglevel warning
    volumes: 
      - cache:/data
    networks:
      - backend
  db:
    image: postgres:13
    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    networks:
      - backend

  backend:
    depends_on:
      - db
      - cache
    ports:
      - "8000:8000"
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - backend
    volumes:
      - ./alembic/versions:/app/alembic/versions
      - ./app/media:/app/app/media
    command: >
      bash -c "alembic revision --autogenerate -m \"first db creation\" 
      && alembic upgrade head 
      && python arq_runner.py
      && (arq arq_runner.WorkerSettings &)
      && uvicorn app.main:app --host 0.0.0.0 --port 8000"

volumes:
  app-db-data:
    driver: local
  cache:
    driver: local

networks:
  backend:
    driver: bridge
