"""first db creation

Revision ID: 0fe56545079e
Revises: 7ff6412f3869
Create Date: 2023-12-05 00:37:15.081649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fe56545079e'
down_revision: Union[str, None] = '7ff6412f3869'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('t_e')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_e',
    sa.Column('docs', sa.TEXT(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
