"""Post.plain_text

Revision ID: cf9308b5d1bb
Revises: 2e3b4fd050df
Create Date: 2023-09-17 06:36:30.479705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf9308b5d1bb'
down_revision: Union[str, None] = '2e3b4fd050df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('plain_text', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'plain_text')
    # ### end Alembic commands ###
